[formatter.black]
command = "black"
includes = [
  "*.py",
]

[formatter.mdformat]
command = "mdformat"
includes = [
  "*.md",
]

[formatter.mh_lint]
command = "mh_lint"
includes = [
  "*.m",
]

[formatter.mh_style]
command = "mh_style"
options = [
  "--fix",
]
includes = [
  "*.m",
]

[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.ruff]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[formatter.shfmt]
command = "shfmt"
options = [
  "--write",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml-sort]
command = "toml-sort"
includes = [
  "*.toml",
]

[formatter.yamlfmt]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
]

[formatter.yamllint]
command = "yamllint"
includes = [
  "*.yaml",
  "*.yml",
]

[global]
excludes = [
  "*.gitignore",
  "*.lock",
  ".editorconfig",
  "LICENSE.md",
  "miss_hit.cfg",
]
